apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nser
  namespace: webapps
spec:
  ports:
  - nodePort: 32333
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: NodePort
